theme: jekyll-theme-cayman
favicon: /image/favicon.ico
small: /image/favicon-16x16.png  
medium: /image/favicon-32x32.png  
apple_touch_icon: /image/apple-touch-icon.png  
safari_pinned_tab: /image/safari-pinned-tab.svg

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: article
      author: zorchp # 添加这一行
      sharing: true
      license: true
      aside:
        toc: true
      show_edit_on_github: true
      show_subscribe: true
      pageview: true
